### ISSUE TITLE
Use the supplied SQL scripts of the addons

### ISSUE THREAD

**Issue by tkrille** [osiam/vagrant#2]
At this time, a big "setup" SQL script is used so create clients, extension, etc. that are needed by the addons. This is due to issues in the upstream projects, that have been fixed but not released yet. As soon as these fixes have been released we should get rid of the `setup_data.sql` and directly use the stuff from  the addons.

**Comment by dacrome** [comment]
:+1:

**Comment by tkrille** [comment]
See also the discussion here: https://github.com/osiam/vagrant/pull/1#discussion_r30488470

**Comment by dacrome** [comment]
This is done with [these lines](https://github.com/osiam/vagrant/blob/master/bootstrap.sh#L66).
