### ISSUE TITLE
What should we use to replace the main distribution for initial installation?

### ISSUE THREAD

**Issue by tkrille** [osiam/vagrant#21]
As [the main distribution has been abandoned](https://github.com/osiam/osiam/issues/93), the Vagrant VM has to be changed to use some other source for initial installation. There are several options:
1. the single distributions
2. the upstream sources on GitHub
3. the mounted sources from the user

Each one has significant drawbacks:
1. Can only install releases. This is the same problem as with the main distribution.
2. Where should we check them out? There are already the mounted sources from the user, if he chooses to do so. Feels like duplication.
3. Some users might not clone the sources and mount them, but simply using the Vagrant VM for integration and exploration.

Number 2. works really well in the current Docker images, so I'd vote for this option.

What's your opinion?

Part of: osiam/osiam#93

**Comment by dacrome** [comment]
I think the sources from GitHub (2.) is the best place.
It should be done like it is in the [docker-image](https://github.com/osiam/docker-image/blob/master/build.conf). The vagrant VM is for development. If you like to create the VM with a release you can change the sources to be checkout to a specific release tag (e.g. OSIAM_REF=v2.5) or you just copy the released war to the tomcat. If you like to test something in the vagrant VM, you don't want to create the VM again, it's easier to copy a changed war which is created before with the mounted sources...
