### ISSUE TITLE
Provide simple smtp server

### ISSUE THREAD

**Issue by dacrome** [osiam/vagrant#4]
To handle the email notification of the self-administration a simple smtp server should be running in the VM. We already using the [greenmail webapp](http://www.icegreen.com/greenmail/#deploy_webapp) to handle this in the integration-tests, maybe this is also a good solution for the vagrant VM? Any other ideas?

**Comment by wallner** [comment]
I don't think that is a good idea. If you want to run osiam you nieed to provide a SMTP server anyway. We could point to [nullmailer](http://untroubled.org/nullmailer/) or something similar, but providing one is not a good idea and might even result in reduced security of the system osiam is installed on. Running a mailer is surely out of scope of osiam in my opinion.

**Comment by dacrome** [comment]
The vagrant vm is not for running in production, this is an easy to use development environment. Everything should be up and testable, so like the self-administration. I think greenmail is a good choice for this use case.

**Comment by tkrille** [comment]
A minimal postfix/qmail/etc. would do the trick, too. But Greenmail sounds viable, as we already have some experience with it.
